services:
  - type: web
    name: ilac-database-app
    env: docker
    plan: pro
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    envVars:
      - key: DATABASE_URI
        value: postgresql://postgres.enrowjcfkauuutemluhd:Alnesuse200824_@aws-0-eu-central-1.pooler.supabase.com:5432/postgres
      - key: PYTHONUNBUFFERED
        value: 1
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8000
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1
    healthCheckPath: /health
    postdeploy:
      - flask db upgrade