services:
  - type: web
    name: drugly
    env: docker
    plan: pro
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URI
        value: postgresql://postgres.enrowjcfkauuutemluhd:Alnesuse200824_@aws-0-eu-central-1.pooler.supabase.com:5432/postgres
    disk:
      name: uploads
      mountPath: /app/static/uploads
      sizeGB: 1
    postdeploy:
      - flask db upgrade