"""empty message

Revision ID: 25167224e493
Revises: 326ebf76bee1
Create Date: 2025-11-20 13:17:08.637685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25167224e493'
down_revision = '326ebf76bee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('event_value', sa.Float(), nullable=True))

    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_clicks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_scrolls', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_errors', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mobile_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tablet_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('desktop_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_page_load_time', sa.Float(), nullable=True))

    with op.batch_alter_table('drug_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sections_viewed', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('scroll_depth', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interactions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bookmarked', sa.Boolean(), nullable=True))

    with op.batch_alter_table('interaction_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_food_interactions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('checked_disease_interactions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('checked_lab_interactions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('time_spent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exported', sa.Boolean(), nullable=True))

    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('time_on_page', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scroll_depth', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exit_page', sa.Boolean(), nullable=True))

    with op.batch_alter_table('search_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clicked_result_position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clicked_result_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_to_first_click', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refined_query', sa.Boolean(), nullable=True))

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('screen_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('screen_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('viewport_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('viewport_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('color_depth', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pixel_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('connection_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('device_memory', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hardware_concurrency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('accuracy', sa.Float(), nullable=True))

    with op.batch_alter_table('visitor_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_brand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('device_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_bot', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_touch_capable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('entry_page', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('exit_page', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_clicks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_scrolls', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_scroll_depth', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_session', schema=None) as batch_op:
        batch_op.drop_column('max_scroll_depth')
        batch_op.drop_column('total_scrolls')
        batch_op.drop_column('total_clicks')
        batch_op.drop_column('exit_page')
        batch_op.drop_column('entry_page')
        batch_op.drop_column('is_touch_capable')
        batch_op.drop_column('is_bot')
        batch_op.drop_column('device_model')
        batch_op.drop_column('device_brand')

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_column('accuracy')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('hardware_concurrency')
        batch_op.drop_column('device_memory')
        batch_op.drop_column('connection_type')
        batch_op.drop_column('pixel_ratio')
        batch_op.drop_column('color_depth')
        batch_op.drop_column('viewport_height')
        batch_op.drop_column('viewport_width')
        batch_op.drop_column('screen_height')
        batch_op.drop_column('screen_width')
        batch_op.drop_column('language')

    with op.batch_alter_table('variant_pheno_ann', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_pheno_ann_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('variant_fa_ann', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_fa_ann_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('variant_drug_ann', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_drug_ann_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('variant_annotation_variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_annotation_variant_variant_id_fkey', 'variant', ['variant_id'], ['id'])
        batch_op.create_foreign_key('variant_annotation_variant_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('variant_annotation_gene', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_annotation_gene_gene_id_fkey', 'gene', ['gene_id'], ['gene_id'])
        batch_op.create_foreign_key('variant_annotation_gene_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('variant_annotation_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_annotation_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('variant_annotation_drug_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('user_scroll', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_scroll_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user_click', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_click_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('sut_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sut_item_version_id_fkey', 'sut_version', ['version_id'], ['id'])

    with op.batch_alter_table('sut_change', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sut_change_version_id_fkey', 'sut_version', ['version_id'], ['id'])

    with op.batch_alter_table('study_parameters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('study_parameters_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('search_query', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('search_query_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('refined_query')
        batch_op.drop_column('time_to_first_click')
        batch_op.drop_column('clicked_result_id')
        batch_op.drop_column('clicked_result_position')

    with op.batch_alter_table('route_of_administration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('route_of_administration_parent_id_fkey', 'route_of_administration', ['parent_id'], ['id'])

    with op.batch_alter_table('route_indication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('route_indication_indication_id_fkey', 'indication', ['indication_id'], ['id'])
        batch_op.create_foreign_key('route_indication_drug_detail_id_fkey', 'drug_detail', ['drug_detail_id'], ['id'])
        batch_op.create_foreign_key('route_indication_route_id_fkey', 'route_of_administration', ['route_id'], ['id'])
        batch_op.create_foreign_key('route_indication_drug_route_id_fkey', 'drug_route', ['drug_route_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pathway_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pathway_drug_pathway_id_fkey', 'pathway', ['pathway_id'], ['id'])
        batch_op.create_foreign_key('pathway_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.drop_column('exit_page')
        batch_op.drop_column('scroll_depth')
        batch_op.drop_column('time_on_page')
        batch_op.drop_column('page_title')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('metabolite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('metabolite_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('metabolite_parent_id_fkey', 'metabolite', ['parent_id'], ['id'])

    with op.batch_alter_table('lab_test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('lab_test_unit_id_fkey', 'unit', ['unit_id'], ['id'])

    with op.batch_alter_table('interaction_route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('interaction_route_interaction_id_fkey', 'drug_interaction', ['interaction_id'], ['id'])
        batch_op.create_foreign_key('interaction_route_route_id_fkey', 'route_of_administration', ['route_id'], ['id'])

    with op.batch_alter_table('interaction_check', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('interaction_check_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('exported')
        batch_op.drop_column('time_spent')
        batch_op.drop_column('checked_lab_interactions')
        batch_op.drop_column('checked_disease_interactions')
        batch_op.drop_column('checked_food_interactions')

    with op.batch_alter_table('indication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('indication_parent_id_fkey', 'indication', ['parent_id'], ['id'])

    with op.batch_alter_table('form_submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('form_submission_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('error_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('error_log_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('drug_view', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_view_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_view_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('bookmarked')
        batch_op.drop_column('shared')
        batch_op.drop_column('interactions')
        batch_op.drop_column('scroll_depth')
        batch_op.drop_column('sections_viewed')

    with op.batch_alter_table('drug_salt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_salt_salt_id_fkey', 'salt', ['salt_id'], ['id'])
        batch_op.create_foreign_key('drug_salt_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('drug_route_metabolite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_route_metabolite_drug_route_id_fkey', 'drug_route', ['drug_route_id'], ['id'])
        batch_op.create_foreign_key('drug_route_metabolite_metabolite_id_fkey', 'metabolite', ['metabolite_id'], ['id'])

    with op.batch_alter_table('drug_route_metabolism_organ', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_route_metabolism_organ_drug_route_id_fkey', 'drug_route', ['drug_route_id'], ['id'])
        batch_op.create_foreign_key('drug_route_metabolism_organ_metabolism_organ_id_fkey', 'metabolism_organ', ['metabolism_organ_id'], ['id'])

    with op.batch_alter_table('drug_route_metabolism_enzyme', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_route_metabolism_enzyme_drug_route_id_fkey', 'drug_route', ['drug_route_id'], ['id'])
        batch_op.create_foreign_key('drug_route_metabolism_enzyme_metabolism_enzyme_id_fkey', 'metabolism_enzyme', ['metabolism_enzyme_id'], ['id'])

    with op.batch_alter_table('drug_route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_route_route_id_fkey', 'route_of_administration', ['route_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('drug_route_therapeutic_unit_id_fkey', 'unit', ['therapeutic_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_half_life_unit_id_fkey', 'unit', ['half_life_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_cmax_unit_id_fkey', 'unit', ['cmax_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_clearance_rate_unit_id_fkey', 'unit', ['clearance_rate_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_vod_rate_unit_id_fkey', 'unit', ['vod_rate_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_tmax_unit_id_fkey', 'unit', ['tmax_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_drug_detail_id_fkey', 'drug_detail', ['drug_detail_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('drug_route_absorption_rate_unit_id_fkey', 'unit', ['absorption_rate_unit_id'], ['id'])

    with op.batch_alter_table('drug_receptor_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_receptor_interaction_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_receptor_interaction_receptor_id_fkey', 'receptor', ['receptor_id'], ['id'])

    with op.batch_alter_table('drug_label_variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_label_variant_pharmgkb_id_fkey', 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'])
        batch_op.create_foreign_key('drug_label_variant_variant_id_fkey', 'variant', ['variant_id'], ['id'])

    with op.batch_alter_table('drug_label_gene', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_label_gene_pharmgkb_id_fkey', 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'])
        batch_op.create_foreign_key('drug_label_gene_gene_id_fkey', 'gene', ['gene_id'], ['gene_id'])

    with op.batch_alter_table('drug_label_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_label_drug_pharmgkb_id_fkey', 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'])
        batch_op.create_foreign_key('drug_label_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('drug_lab_test_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_lab_test_interaction_severity_id_fkey', 'severity', ['severity_id'], ['id'])
        batch_op.create_foreign_key('drug_lab_test_interaction_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_lab_test_interaction_lab_test_id_fkey', 'lab_test', ['lab_test_id'], ['id'])

    with op.batch_alter_table('drug_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_interaction_drug1_id_fkey', 'drug', ['drug1_id'], ['id'])
        batch_op.create_foreign_key('drug_interaction_drug2_id_fkey', 'drug', ['drug2_id'], ['id'])
        batch_op.create_foreign_key('drug_interaction_severity_id_fkey', 'severity', ['severity_id'], ['id'])

    with op.batch_alter_table('drug_food_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_food_interaction_food_id_fkey', 'food', ['food_id'], ['id'])
        batch_op.create_foreign_key('drug_food_interaction_severity_id_fkey', 'severity', ['severity_id'], ['id'])
        batch_op.create_foreign_key('drug_food_interaction_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('drug_disease_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_disease_interaction_indication_id_fkey', 'indication', ['indication_id'], ['id'])
        batch_op.create_foreign_key('drug_disease_interaction_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('drug_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_detail_solubility_unit_id_fkey', 'unit', ['solubility_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_flash_point_unit_id_fkey', 'unit', ['flash_point_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_pregnancy_safety_trimester2_id_fkey', 'safety_category', ['pregnancy_safety_trimester2_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_half_life_unit_id_fkey', 'unit', ['half_life_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_molecular_weight_unit_id_fkey', 'unit', ['molecular_weight_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_salt_id_fkey', 'salt', ['salt_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_lactation_safety_id_fkey', 'safety_category', ['lactation_safety_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_pregnancy_safety_trimester3_id_fkey', 'safety_category', ['pregnancy_safety_trimester3_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_pregnancy_safety_trimester1_id_fkey', 'safety_category', ['pregnancy_safety_trimester1_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_density_unit_id_fkey', 'unit', ['density_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_melting_point_unit_id_fkey', 'unit', ['melting_point_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_clearance_rate_unit_id_fkey', 'unit', ['clearance_rate_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_boiling_point_unit_id_fkey', 'unit', ['boiling_point_unit_id'], ['id'])

    with op.batch_alter_table('drug_category_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_category_association_category_id_fkey', 'drug_category', ['category_id'], ['id'])
        batch_op.create_foreign_key('drug_category_association_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('drug_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_category_parent_id_fkey', 'drug_category', ['parent_id'], ['id'])

    with op.batch_alter_table('drug_atc_mapping', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_atc_mapping_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_atc_mapping_atc_level5_id_fkey', 'atc_level5', ['atc_level5_id'], ['id'])

    with op.batch_alter_table('detail_side_effect', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('detail_side_effect_side_effect_id_fkey', 'side_effect', ['side_effect_id'], ['id'])
        batch_op.create_foreign_key('detail_side_effect_detail_id_fkey', 'drug_detail', ['detail_id'], ['id'])

    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.drop_column('avg_page_load_time')
        batch_op.drop_column('desktop_percentage')
        batch_op.drop_column('tablet_percentage')
        batch_op.drop_column('mobile_percentage')
        batch_op.drop_column('total_errors')
        batch_op.drop_column('total_scrolls')
        batch_op.drop_column('total_clicks')

    with op.batch_alter_table('clinical_variants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_variants_gene_id_fkey', 'gene', ['gene_id'], ['gene_id'])

    with op.batch_alter_table('clinical_variant_variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_variant_variant_clinical_variant_id_fkey', 'clinical_variants', ['clinical_variant_id'], ['id'])
        batch_op.create_foreign_key('clinical_variant_variant_variant_id_fkey', 'variant', ['variant_id'], ['id'])

    with op.batch_alter_table('clinical_variant_phenotype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_variant_phenotype_phenotype_id_fkey', 'phenotype', ['phenotype_id'], ['id'])
        batch_op.create_foreign_key('clinical_variant_phenotype_clinical_variant_id_fkey', 'clinical_variants', ['clinical_variant_id'], ['id'])

    with op.batch_alter_table('clinical_variant_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_variant_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('clinical_variant_drug_clinical_variant_id_fkey', 'clinical_variants', ['clinical_variant_id'], ['id'])

    with op.batch_alter_table('clinical_annotation_variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_annotation_variant_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])
        batch_op.create_foreign_key('clinical_annotation_variant_variant_id_fkey', 'variant', ['variant_id'], ['id'])

    with op.batch_alter_table('clinical_annotation_phenotype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_annotation_phenotype_phenotype_id_fkey', 'phenotype', ['phenotype_id'], ['id'])
        batch_op.create_foreign_key('clinical_annotation_phenotype_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])

    with op.batch_alter_table('clinical_annotation_gene', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_annotation_gene_gene_id_fkey', 'gene', ['gene_id'], ['gene_id'])
        batch_op.create_foreign_key('clinical_annotation_gene_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])

    with op.batch_alter_table('clinical_annotation_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_annotation_drug_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])
        batch_op.create_foreign_key('clinical_annotation_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('clinical_ann_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_ann_history_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])

    with op.batch_alter_table('clinical_ann_evidence_publication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_ann_evidence_publication_evidence_id_fkey', 'clinical_ann_evidence', ['evidence_id'], ['evidence_id'])
        batch_op.create_foreign_key('clinical_ann_evidence_publication_pmid_fkey', 'publication', ['pmid'], ['pmid'])

    with op.batch_alter_table('clinical_ann_evidence', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_ann_evidence_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])

    with op.batch_alter_table('clinical_ann_allele', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_ann_allele_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])

    with op.batch_alter_table('automated_annotations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('automated_annotations_pmid_fkey', 'publication', ['pmid'], ['pmid'])

    with op.batch_alter_table('atc_level5', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('atc_level5_level4_id_fkey', 'atc_level4', ['level4_id'], ['id'])

    with op.batch_alter_table('atc_level4', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('atc_level4_level3_id_fkey', 'atc_level3', ['level3_id'], ['id'])

    with op.batch_alter_table('atc_level3', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('atc_level3_level2_id_fkey', 'atc_level2', ['level2_id'], ['id'])

    with op.batch_alter_table('atc_level2', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('atc_level2_level1_id_fkey', 'atc_level1', ['level1_id'], ['id'])

    with op.batch_alter_table('analytics_event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('analytics_event_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('event_value')
        batch_op.drop_column('page_url')

    # ### end Alembic commands ###
