"""empty message

Revision ID: 3ec9e43327cf
Revises: d9023785a821
Create Date: 2025-11-14 23:24:41.005550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec9e43327cf'
down_revision = 'd9023785a821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sut_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sut_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('change_date', sa.DateTime(), nullable=True),
    sa.Column('item_number', sa.String(length=50), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('old_content', sa.Text(), nullable=True),
    sa.Column('new_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['sut_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sut_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('parent_number', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['sut_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sut_item', schema=None) as batch_op:
        batch_op.create_index('idx_version_item', ['version_id', 'item_number'], unique=False)
        batch_op.create_index('idx_version_parent', ['version_id', 'parent_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sut_item_item_number'), ['item_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sut_item_parent_number'), ['parent_number'], unique=False)

    with op.batch_alter_table('automated_annotations', schema=None) as batch_op:
        batch_op.drop_constraint('automated_annotations_pmid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publication', ['pmid'], ['pmid'], referent_schema='public')

    with op.batch_alter_table('clinical_ann_allele', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_ann_allele_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')

    with op.batch_alter_table('clinical_ann_evidence', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_ann_evidence_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')

    with op.batch_alter_table('clinical_ann_evidence_publication', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_ann_evidence_publication_evidence_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_ann_evidence_publication_pmid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_ann_evidence', ['evidence_id'], ['evidence_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'publication', ['pmid'], ['pmid'], referent_schema='public')

    with op.batch_alter_table('clinical_ann_history', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_ann_history_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')

    with op.batch_alter_table('clinical_annotation_drug', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_annotation_drug_drug_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_annotation_drug_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')

    with op.batch_alter_table('clinical_annotation_gene', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_annotation_gene_gene_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_annotation_gene_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'gene', ['gene_id'], ['gene_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')

    with op.batch_alter_table('clinical_annotation_phenotype', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_annotation_phenotype_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_annotation_phenotype_phenotype_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'phenotype', ['phenotype_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('clinical_annotation_variant', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_annotation_variant_variant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_annotation_variant_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'variant', ['variant_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('clinical_variant_drug', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_variant_drug_drug_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_variant_drug_clinical_variant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'clinical_variants', ['clinical_variant_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('clinical_variant_phenotype', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_variant_phenotype_clinical_variant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_variant_phenotype_phenotype_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'phenotype', ['phenotype_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'clinical_variants', ['clinical_variant_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('clinical_variant_variant', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_variant_variant_variant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_variant_variant_clinical_variant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant', ['variant_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'clinical_variants', ['clinical_variant_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('clinical_variants', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_variants_gene_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'gene', ['gene_id'], ['gene_id'], referent_schema='public')

    with op.batch_alter_table('detail_side_effect', schema=None) as batch_op:
        batch_op.drop_constraint('detail_side_effect_detail_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('detail_side_effect_side_effect_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'side_effect', ['side_effect_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug_detail', ['detail_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_category', schema=None) as batch_op:
        batch_op.drop_constraint('drug_category_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_category', ['parent_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_category_association', schema=None) as batch_op:
        batch_op.drop_constraint('drug_category_association_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_category_association_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug_category', ['category_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_detail', schema=None) as batch_op:
        batch_op.drop_constraint('drug_detail_lactation_safety_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_boiling_point_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_clearance_rate_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_solubility_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_pregnancy_safety_trimester3_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_melting_point_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_pregnancy_safety_trimester2_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_drug_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_half_life_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_density_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_pregnancy_safety_trimester1_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_flash_point_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_molecular_weight_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_salt_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'unit', ['flash_point_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'unit', ['density_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'unit', ['melting_point_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'unit', ['solubility_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'salt', ['salt_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'safety_category', ['pregnancy_safety_trimester1_id'], ['id'])
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'safety_category', ['pregnancy_safety_trimester3_id'], ['id'])
        batch_op.create_foreign_key(None, 'unit', ['half_life_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'safety_category', ['lactation_safety_id'], ['id'])
        batch_op.create_foreign_key(None, 'unit', ['boiling_point_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'unit', ['molecular_weight_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'unit', ['clearance_rate_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'safety_category', ['pregnancy_safety_trimester2_id'], ['id'])

    with op.batch_alter_table('drug_disease_interaction', schema=None) as batch_op:
        batch_op.drop_constraint('drug_disease_interaction_indication_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_disease_interaction_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'indication', ['indication_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_food_interaction', schema=None) as batch_op:
        batch_op.drop_constraint('drug_food_interaction_severity_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_food_interaction_food_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_food_interaction_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'severity', ['severity_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'food', ['food_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_interaction', schema=None) as batch_op:
        batch_op.drop_constraint('drug_interaction_severity_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_interaction_drug2_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_interaction_drug1_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'severity', ['severity_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug1_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug2_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_lab_test_interaction', schema=None) as batch_op:
        batch_op.drop_constraint('drug_lab_test_interaction_severity_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_lab_test_interaction_lab_test_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_lab_test_interaction_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lab_test', ['lab_test_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'severity', ['severity_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_label_drug', schema=None) as batch_op:
        batch_op.drop_constraint('drug_label_drug_drug_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_label_drug_pharmgkb_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'], referent_schema='public')

    with op.batch_alter_table('drug_label_gene', schema=None) as batch_op:
        batch_op.drop_constraint('drug_label_gene_gene_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_label_gene_pharmgkb_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'gene', ['gene_id'], ['gene_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'], referent_schema='public')

    with op.batch_alter_table('drug_label_variant', schema=None) as batch_op:
        batch_op.drop_constraint('drug_label_variant_variant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_label_variant_pharmgkb_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'variant', ['variant_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_receptor_interaction', schema=None) as batch_op:
        batch_op.drop_constraint('drug_receptor_interaction_drug_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_receptor_interaction_receptor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'receptor', ['receptor_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_route', schema=None) as batch_op:
        batch_op.drop_constraint('drug_route_drug_detail_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_vod_rate_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_therapeutic_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_absorption_rate_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_tmax_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_half_life_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_clearance_rate_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_cmax_unit_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_route_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'unit', ['vod_rate_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'unit', ['clearance_rate_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug_detail', ['drug_detail_id'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'unit', ['half_life_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'unit', ['therapeutic_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'unit', ['tmax_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'unit', ['absorption_rate_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'unit', ['cmax_unit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'route_of_administration', ['route_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('drug_route_metabolism_enzyme', schema=None) as batch_op:
        batch_op.drop_constraint('drug_route_metabolism_enzyme_drug_route_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_metabolism_enzyme_metabolism_enzyme_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_route', ['drug_route_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'metabolism_enzyme', ['metabolism_enzyme_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_route_metabolism_organ', schema=None) as batch_op:
        batch_op.drop_constraint('drug_route_metabolism_organ_metabolism_organ_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_metabolism_organ_drug_route_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_route', ['drug_route_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'metabolism_organ', ['metabolism_organ_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_route_metabolite', schema=None) as batch_op:
        batch_op.drop_constraint('drug_route_metabolite_metabolite_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_metabolite_drug_route_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'metabolite', ['metabolite_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug_route', ['drug_route_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_salt', schema=None) as batch_op:
        batch_op.drop_constraint('drug_salt_salt_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_salt_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'salt', ['salt_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('indication', schema=None) as batch_op:
        batch_op.drop_constraint('indication_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'indication', ['parent_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('interaction_route', schema=None) as batch_op:
        batch_op.drop_constraint('interaction_route_route_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('interaction_route_interaction_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_interaction', ['interaction_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'route_of_administration', ['route_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('lab_test', schema=None) as batch_op:
        batch_op.drop_constraint('lab_test_unit_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'unit', ['unit_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('metabolite', schema=None) as batch_op:
        batch_op.drop_constraint('metabolite_parent_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('metabolite_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'metabolite', ['parent_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('pathway_drug', schema=None) as batch_op:
        batch_op.drop_constraint('pathway_drug_pathway_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('pathway_drug_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pathway', ['pathway_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('route_indication', schema=None) as batch_op:
        batch_op.drop_constraint('route_indication_route_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('route_indication_drug_route_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('route_indication_indication_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('route_indication_drug_detail_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'route_of_administration', ['route_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'indication', ['indication_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug_route', ['drug_route_id'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'drug_detail', ['drug_detail_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('route_of_administration', schema=None) as batch_op:
        batch_op.drop_constraint('route_of_administration_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'route_of_administration', ['parent_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('study_parameters', schema=None) as batch_op:
        batch_op.drop_constraint('study_parameters_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')

    with op.batch_alter_table('variant_annotation_drug', schema=None) as batch_op:
        batch_op.drop_constraint('variant_annotation_drug_drug_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('variant_annotation_drug_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('variant_annotation_gene', schema=None) as batch_op:
        batch_op.drop_constraint('variant_annotation_gene_gene_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('variant_annotation_gene_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'gene', ['gene_id'], ['gene_id'], referent_schema='public')

    with op.batch_alter_table('variant_annotation_variant', schema=None) as batch_op:
        batch_op.drop_constraint('variant_annotation_variant_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('variant_annotation_variant_variant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'variant', ['variant_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('variant_drug_ann', schema=None) as batch_op:
        batch_op.drop_constraint('variant_drug_ann_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')

    with op.batch_alter_table('variant_fa_ann', schema=None) as batch_op:
        batch_op.drop_constraint('variant_fa_ann_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')

    with op.batch_alter_table('variant_pheno_ann', schema=None) as batch_op:
        batch_op.drop_constraint('variant_pheno_ann_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant_pheno_ann', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_pheno_ann_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('variant_fa_ann', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_fa_ann_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('variant_drug_ann', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_drug_ann_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('variant_annotation_variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_annotation_variant_variant_id_fkey', 'variant', ['variant_id'], ['id'])
        batch_op.create_foreign_key('variant_annotation_variant_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('variant_annotation_gene', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_annotation_gene_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])
        batch_op.create_foreign_key('variant_annotation_gene_gene_id_fkey', 'gene', ['gene_id'], ['gene_id'])

    with op.batch_alter_table('variant_annotation_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_annotation_drug_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])
        batch_op.create_foreign_key('variant_annotation_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('study_parameters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('study_parameters_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('route_of_administration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('route_of_administration_parent_id_fkey', 'route_of_administration', ['parent_id'], ['id'])

    with op.batch_alter_table('route_indication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('route_indication_drug_detail_id_fkey', 'drug_detail', ['drug_detail_id'], ['id'])
        batch_op.create_foreign_key('route_indication_indication_id_fkey', 'indication', ['indication_id'], ['id'])
        batch_op.create_foreign_key('route_indication_drug_route_id_fkey', 'drug_route', ['drug_route_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('route_indication_route_id_fkey', 'route_of_administration', ['route_id'], ['id'])

    with op.batch_alter_table('pathway_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pathway_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('pathway_drug_pathway_id_fkey', 'pathway', ['pathway_id'], ['id'])

    with op.batch_alter_table('metabolite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('metabolite_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('metabolite_parent_id_fkey', 'metabolite', ['parent_id'], ['id'])

    with op.batch_alter_table('lab_test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('lab_test_unit_id_fkey', 'unit', ['unit_id'], ['id'])

    with op.batch_alter_table('interaction_route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('interaction_route_interaction_id_fkey', 'drug_interaction', ['interaction_id'], ['id'])
        batch_op.create_foreign_key('interaction_route_route_id_fkey', 'route_of_administration', ['route_id'], ['id'])

    with op.batch_alter_table('indication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('indication_parent_id_fkey', 'indication', ['parent_id'], ['id'])

    with op.batch_alter_table('drug_salt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_salt_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_salt_salt_id_fkey', 'salt', ['salt_id'], ['id'])

    with op.batch_alter_table('drug_route_metabolite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_route_metabolite_drug_route_id_fkey', 'drug_route', ['drug_route_id'], ['id'])
        batch_op.create_foreign_key('drug_route_metabolite_metabolite_id_fkey', 'metabolite', ['metabolite_id'], ['id'])

    with op.batch_alter_table('drug_route_metabolism_organ', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_route_metabolism_organ_drug_route_id_fkey', 'drug_route', ['drug_route_id'], ['id'])
        batch_op.create_foreign_key('drug_route_metabolism_organ_metabolism_organ_id_fkey', 'metabolism_organ', ['metabolism_organ_id'], ['id'])

    with op.batch_alter_table('drug_route_metabolism_enzyme', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_route_metabolism_enzyme_metabolism_enzyme_id_fkey', 'metabolism_enzyme', ['metabolism_enzyme_id'], ['id'])
        batch_op.create_foreign_key('drug_route_metabolism_enzyme_drug_route_id_fkey', 'drug_route', ['drug_route_id'], ['id'])

    with op.batch_alter_table('drug_route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_route_route_id_fkey', 'route_of_administration', ['route_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('drug_route_cmax_unit_id_fkey', 'unit', ['cmax_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_clearance_rate_unit_id_fkey', 'unit', ['clearance_rate_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_half_life_unit_id_fkey', 'unit', ['half_life_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_tmax_unit_id_fkey', 'unit', ['tmax_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_absorption_rate_unit_id_fkey', 'unit', ['absorption_rate_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_therapeutic_unit_id_fkey', 'unit', ['therapeutic_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_vod_rate_unit_id_fkey', 'unit', ['vod_rate_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_route_drug_detail_id_fkey', 'drug_detail', ['drug_detail_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('drug_receptor_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_receptor_interaction_receptor_id_fkey', 'receptor', ['receptor_id'], ['id'])
        batch_op.create_foreign_key('drug_receptor_interaction_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('drug_label_variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_label_variant_pharmgkb_id_fkey', 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'])
        batch_op.create_foreign_key('drug_label_variant_variant_id_fkey', 'variant', ['variant_id'], ['id'])

    with op.batch_alter_table('drug_label_gene', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_label_gene_pharmgkb_id_fkey', 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'])
        batch_op.create_foreign_key('drug_label_gene_gene_id_fkey', 'gene', ['gene_id'], ['gene_id'])

    with op.batch_alter_table('drug_label_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_label_drug_pharmgkb_id_fkey', 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'])
        batch_op.create_foreign_key('drug_label_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('drug_lab_test_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_lab_test_interaction_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_lab_test_interaction_lab_test_id_fkey', 'lab_test', ['lab_test_id'], ['id'])
        batch_op.create_foreign_key('drug_lab_test_interaction_severity_id_fkey', 'severity', ['severity_id'], ['id'])

    with op.batch_alter_table('drug_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_interaction_drug1_id_fkey', 'drug', ['drug1_id'], ['id'])
        batch_op.create_foreign_key('drug_interaction_drug2_id_fkey', 'drug', ['drug2_id'], ['id'])
        batch_op.create_foreign_key('drug_interaction_severity_id_fkey', 'severity', ['severity_id'], ['id'])

    with op.batch_alter_table('drug_food_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_food_interaction_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_food_interaction_food_id_fkey', 'food', ['food_id'], ['id'])
        batch_op.create_foreign_key('drug_food_interaction_severity_id_fkey', 'severity', ['severity_id'], ['id'])

    with op.batch_alter_table('drug_disease_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_disease_interaction_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_disease_interaction_indication_id_fkey', 'indication', ['indication_id'], ['id'])

    with op.batch_alter_table('drug_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_detail_salt_id_fkey', 'salt', ['salt_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_molecular_weight_unit_id_fkey', 'unit', ['molecular_weight_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_flash_point_unit_id_fkey', 'unit', ['flash_point_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_pregnancy_safety_trimester1_id_fkey', 'safety_category', ['pregnancy_safety_trimester1_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_density_unit_id_fkey', 'unit', ['density_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_half_life_unit_id_fkey', 'unit', ['half_life_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_pregnancy_safety_trimester2_id_fkey', 'safety_category', ['pregnancy_safety_trimester2_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_melting_point_unit_id_fkey', 'unit', ['melting_point_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_pregnancy_safety_trimester3_id_fkey', 'safety_category', ['pregnancy_safety_trimester3_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_solubility_unit_id_fkey', 'unit', ['solubility_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_clearance_rate_unit_id_fkey', 'unit', ['clearance_rate_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_boiling_point_unit_id_fkey', 'unit', ['boiling_point_unit_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_lactation_safety_id_fkey', 'safety_category', ['lactation_safety_id'], ['id'])

    with op.batch_alter_table('drug_category_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_category_association_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_category_association_category_id_fkey', 'drug_category', ['category_id'], ['id'])

    with op.batch_alter_table('drug_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_category_parent_id_fkey', 'drug_category', ['parent_id'], ['id'])

    with op.batch_alter_table('detail_side_effect', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('detail_side_effect_side_effect_id_fkey', 'side_effect', ['side_effect_id'], ['id'])
        batch_op.create_foreign_key('detail_side_effect_detail_id_fkey', 'drug_detail', ['detail_id'], ['id'])

    with op.batch_alter_table('clinical_variants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_variants_gene_id_fkey', 'gene', ['gene_id'], ['gene_id'])

    with op.batch_alter_table('clinical_variant_variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_variant_variant_clinical_variant_id_fkey', 'clinical_variants', ['clinical_variant_id'], ['id'])
        batch_op.create_foreign_key('clinical_variant_variant_variant_id_fkey', 'variant', ['variant_id'], ['id'])

    with op.batch_alter_table('clinical_variant_phenotype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_variant_phenotype_phenotype_id_fkey', 'phenotype', ['phenotype_id'], ['id'])
        batch_op.create_foreign_key('clinical_variant_phenotype_clinical_variant_id_fkey', 'clinical_variants', ['clinical_variant_id'], ['id'])

    with op.batch_alter_table('clinical_variant_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_variant_drug_clinical_variant_id_fkey', 'clinical_variants', ['clinical_variant_id'], ['id'])
        batch_op.create_foreign_key('clinical_variant_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('clinical_annotation_variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_annotation_variant_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])
        batch_op.create_foreign_key('clinical_annotation_variant_variant_id_fkey', 'variant', ['variant_id'], ['id'])

    with op.batch_alter_table('clinical_annotation_phenotype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_annotation_phenotype_phenotype_id_fkey', 'phenotype', ['phenotype_id'], ['id'])
        batch_op.create_foreign_key('clinical_annotation_phenotype_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])

    with op.batch_alter_table('clinical_annotation_gene', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_annotation_gene_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])
        batch_op.create_foreign_key('clinical_annotation_gene_gene_id_fkey', 'gene', ['gene_id'], ['gene_id'])

    with op.batch_alter_table('clinical_annotation_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_annotation_drug_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])
        batch_op.create_foreign_key('clinical_annotation_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('clinical_ann_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_ann_history_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])

    with op.batch_alter_table('clinical_ann_evidence_publication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_ann_evidence_publication_pmid_fkey', 'publication', ['pmid'], ['pmid'])
        batch_op.create_foreign_key('clinical_ann_evidence_publication_evidence_id_fkey', 'clinical_ann_evidence', ['evidence_id'], ['evidence_id'])

    with op.batch_alter_table('clinical_ann_evidence', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_ann_evidence_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])

    with op.batch_alter_table('clinical_ann_allele', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_ann_allele_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])

    with op.batch_alter_table('automated_annotations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('automated_annotations_pmid_fkey', 'publication', ['pmid'], ['pmid'])

    with op.batch_alter_table('sut_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sut_item_parent_number'))
        batch_op.drop_index(batch_op.f('ix_sut_item_item_number'))
        batch_op.drop_index('idx_version_parent')
        batch_op.drop_index('idx_version_item')

    op.drop_table('sut_item')
    op.drop_table('sut_change')
    op.drop_table('sut_version')
    # ### end Alembic commands ###
