"""empty message

Revision ID: af67be257fb1
Revises: 18052f54bd72
Create Date: 2025-06-17 13:18:24.418477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af67be257fb1'
down_revision = '18052f54bd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.drop_table('user_progress')
    op.drop_table('case_study')
    with op.batch_alter_table('automated_annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_automated_annotations_chemical_id'), ['chemical_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_automated_annotations_gene_symbols'), ['gene_symbols'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_automated_annotations_pmid'), ['pmid'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_automated_annotations_variation_id'), ['variation_id'], unique=False)
        batch_op.drop_constraint('automated_annotations_pmid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'publication', ['pmid'], ['pmid'], referent_schema='public')

    with op.batch_alter_table('clinical_ann_allele', schema=None) as batch_op:
        batch_op.alter_column('clinical_annotation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_public_clinical_ann_allele_genotype_allele'), ['genotype_allele'], unique=False)
        batch_op.drop_constraint('clinical_ann_allele_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')

    with op.batch_alter_table('clinical_ann_evidence', schema=None) as batch_op:
        batch_op.alter_column('clinical_annotation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_public_clinical_ann_evidence_evidence_type'), ['evidence_type'], unique=False)
        batch_op.drop_constraint('clinical_ann_evidence_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')

    with op.batch_alter_table('clinical_ann_evidence_publication', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_ann_evidence_publication_evidence_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_ann_evidence_publication_pmid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_ann_evidence', ['evidence_id'], ['evidence_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'publication', ['pmid'], ['pmid'], referent_schema='public')

    with op.batch_alter_table('clinical_ann_history', schema=None) as batch_op:
        batch_op.alter_column('clinical_annotation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_public_clinical_ann_history_date'), ['date'], unique=False)
        batch_op.drop_constraint('clinical_ann_history_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')

    with op.batch_alter_table('clinical_annotation_drug', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_annotation_drug_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_annotation_drug_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('clinical_annotation_gene', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_annotation_gene_gene_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_annotation_gene_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'gene', ['gene_id'], ['gene_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')

    with op.batch_alter_table('clinical_annotation_phenotype', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_annotation_phenotype_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_annotation_phenotype_phenotype_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'phenotype', ['phenotype_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('clinical_annotation_variant', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_annotation_variant_clinical_annotation_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_annotation_variant_variant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'variant', ['variant_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('clinical_variant_drug', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_variant_drug_clinical_variant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_variant_drug_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'clinical_variants', ['clinical_variant_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('clinical_variant_phenotype', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_variant_phenotype_clinical_variant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_variant_phenotype_phenotype_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_variants', ['clinical_variant_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'phenotype', ['phenotype_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('clinical_variant_variant', schema=None) as batch_op:
        batch_op.drop_constraint('clinical_variant_variant_variant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('clinical_variant_variant_clinical_variant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinical_variants', ['clinical_variant_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'variant', ['variant_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('clinical_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_clinical_variants_gene_id'), ['gene_id'], unique=False)
        batch_op.drop_constraint('clinical_variants_gene_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'gene', ['gene_id'], ['gene_id'], referent_schema='public')

    with op.batch_alter_table('detail_side_effect', schema=None) as batch_op:
        batch_op.drop_constraint('detail_side_effect_detail_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('detail_side_effect_side_effect_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_detail', ['detail_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'side_effect', ['side_effect_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug', schema=None) as batch_op:
        batch_op.drop_constraint('drug_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_category', ['category_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_category', schema=None) as batch_op:
        batch_op.drop_constraint('drug_category_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_category', ['parent_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_detail', schema=None) as batch_op:
        batch_op.drop_constraint('drug_detail_salt_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_detail_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'salt', ['salt_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_disease_interaction', schema=None) as batch_op:
        batch_op.drop_constraint('drug_disease_interaction_drug_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_disease_interaction_indication_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'indication', ['indication_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_interaction', schema=None) as batch_op:
        batch_op.drop_constraint('drug_interaction_route_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_interaction_drug2_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_interaction_drug1_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('fk_drug_interaction_severity_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug2_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug1_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'severity', ['severity_id'], ['id'], referent_schema='public')
        batch_op.drop_column('route_id')

    with op.batch_alter_table('drug_lab_test_interaction', schema=None) as batch_op:
        batch_op.drop_constraint('drug_lab_test_interaction_lab_test_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_lab_test_interaction_severity_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_lab_test_interaction_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'severity', ['severity_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'lab_test', ['lab_test_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_label_drug', schema=None) as batch_op:
        batch_op.drop_constraint('drug_label_drug_pharmgkb_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_label_drug_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_label_gene', schema=None) as batch_op:
        batch_op.drop_constraint('drug_label_gene_pharmgkb_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_label_gene_gene_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'gene', ['gene_id'], ['gene_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'], referent_schema='public')

    with op.batch_alter_table('drug_label_variant', schema=None) as batch_op:
        batch_op.drop_constraint('drug_label_variant_pharmgkb_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_label_variant_variant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'variant', ['variant_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_receptor_interaction', schema=None) as batch_op:
        batch_op.drop_constraint('drug_receptor_interaction_receptor_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_receptor_interaction_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'receptor', ['receptor_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_route', schema=None) as batch_op:
        batch_op.drop_constraint('drug_route_route_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_drug_detail_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_detail', ['drug_detail_id'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'route_of_administration', ['route_id'], ['id'], referent_schema='public', ondelete='CASCADE')

    with op.batch_alter_table('drug_route_metabolism_enzyme', schema=None) as batch_op:
        batch_op.drop_constraint('drug_route_metabolism_enzyme_metabolism_enzyme_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_metabolism_enzyme_drug_route_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug_route', ['drug_route_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'metabolism_enzyme', ['metabolism_enzyme_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_route_metabolism_organ', schema=None) as batch_op:
        batch_op.drop_constraint('drug_route_metabolism_organ_metabolism_organ_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_metabolism_organ_drug_route_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'metabolism_organ', ['metabolism_organ_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug_route', ['drug_route_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_route_metabolite', schema=None) as batch_op:
        batch_op.drop_constraint('drug_route_metabolite_metabolite_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_route_metabolite_drug_route_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'metabolite', ['metabolite_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug_route', ['drug_route_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('drug_salt', schema=None) as batch_op:
        batch_op.drop_constraint('drug_salt_salt_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('drug_salt_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'salt', ['salt_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('indication', schema=None) as batch_op:
        batch_op.drop_constraint('indication_disease_id_key', type_='unique')
        batch_op.drop_constraint('indication_foundation_uri_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_public_indication_BlockId'), ['BlockId'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_indication_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_indication_disease_id'), ['disease_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_public_indication_foundation_uri'), ['foundation_uri'], unique=True)
        batch_op.create_index(batch_op.f('ix_public_indication_parent_id'), ['parent_id'], unique=False)
        batch_op.drop_constraint('indication_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'indication', ['parent_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('interaction_route', schema=None) as batch_op:
        batch_op.drop_constraint('interaction_route_route_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('interaction_route_interaction_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'route_of_administration', ['route_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug_interaction', ['interaction_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('lab_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'unit', ['unit_id'], ['id'], referent_schema='public')
        batch_op.drop_column('unit')

    with op.batch_alter_table('metabolite', schema=None) as batch_op:
        batch_op.drop_constraint('metabolite_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'metabolite', ['parent_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_occurrences_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_occurrences_source_id'), ['source_id'], unique=False)

    with op.batch_alter_table('pathway_drug', schema=None) as batch_op:
        batch_op.drop_constraint('pathway_drug_drug_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('pathway_drug_pathway_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'pathway', ['pathway_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_relationships_entity1_id'), ['entity1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_relationships_entity2_id'), ['entity2_id'], unique=False)

    with op.batch_alter_table('route_indication', schema=None) as batch_op:
        batch_op.drop_constraint('route_indication_drug_route_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('route_indication_route_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('route_indication_indication_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('route_indication_drug_detail_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'route_of_administration', ['route_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'indication', ['indication_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'drug_route', ['drug_route_id'], ['id'], referent_schema='public', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'drug_detail', ['drug_detail_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('route_of_administration', schema=None) as batch_op:
        batch_op.drop_constraint('route_of_administration_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'route_of_administration', ['parent_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('study_parameters', schema=None) as batch_op:
        batch_op.drop_constraint('study_parameters_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('variant_annotation_drug', schema=None) as batch_op:
        batch_op.drop_constraint('variant_annotation_drug_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('variant_annotation_drug_drug_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drug', ['drug_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')

    with op.batch_alter_table('variant_annotation_gene', schema=None) as batch_op:
        batch_op.drop_constraint('variant_annotation_gene_gene_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('variant_annotation_gene_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'gene', ['gene_id'], ['gene_id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')

    with op.batch_alter_table('variant_annotation_variant', schema=None) as batch_op:
        batch_op.drop_constraint('variant_annotation_variant_variant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('variant_annotation_variant_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant', ['variant_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')

    with op.batch_alter_table('variant_drug_ann', schema=None) as batch_op:
        batch_op.drop_constraint('variant_drug_ann_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')

    with op.batch_alter_table('variant_fa_ann', schema=None) as batch_op:
        batch_op.drop_constraint('variant_fa_ann_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')

    with op.batch_alter_table('variant_pheno_ann', schema=None) as batch_op:
        batch_op.drop_constraint('variant_pheno_ann_variant_annotation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variant_pheno_ann', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_pheno_ann_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('variant_fa_ann', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_fa_ann_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('variant_drug_ann', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_drug_ann_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('variant_annotation_variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_annotation_variant_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])
        batch_op.create_foreign_key('variant_annotation_variant_variant_id_fkey', 'variant', ['variant_id'], ['id'])

    with op.batch_alter_table('variant_annotation_gene', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_annotation_gene_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])
        batch_op.create_foreign_key('variant_annotation_gene_gene_id_fkey', 'gene', ['gene_id'], ['gene_id'])

    with op.batch_alter_table('variant_annotation_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('variant_annotation_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('variant_annotation_drug_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('study_parameters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('study_parameters_variant_annotation_id_fkey', 'variant_annotation', ['variant_annotation_id'], ['variant_annotation_id'])

    with op.batch_alter_table('route_of_administration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('route_of_administration_parent_id_fkey', 'route_of_administration', ['parent_id'], ['id'])

    with op.batch_alter_table('route_indication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('route_indication_drug_detail_id_fkey', 'drug_detail', ['drug_detail_id'], ['id'])
        batch_op.create_foreign_key('route_indication_indication_id_fkey', 'indication', ['indication_id'], ['id'])
        batch_op.create_foreign_key('route_indication_route_id_fkey', 'route_of_administration', ['route_id'], ['id'])
        batch_op.create_foreign_key('route_indication_drug_route_id_fkey', 'drug_route', ['drug_route_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_relationships_entity2_id'))
        batch_op.drop_index(batch_op.f('ix_public_relationships_entity1_id'))

    with op.batch_alter_table('pathway_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pathway_drug_pathway_id_fkey', 'pathway', ['pathway_id'], ['id'])
        batch_op.create_foreign_key('pathway_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_occurrences_source_id'))
        batch_op.drop_index(batch_op.f('ix_public_occurrences_object_id'))

    with op.batch_alter_table('metabolite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('metabolite_parent_id_fkey', 'metabolite', ['parent_id'], ['id'])

    with op.batch_alter_table('lab_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unit_id')

    with op.batch_alter_table('interaction_route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('interaction_route_interaction_id_fkey', 'drug_interaction', ['interaction_id'], ['id'])
        batch_op.create_foreign_key('interaction_route_route_id_fkey', 'route_of_administration', ['route_id'], ['id'])

    with op.batch_alter_table('indication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('indication_parent_id_fkey', 'indication', ['parent_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_public_indication_parent_id'))
        batch_op.drop_index(batch_op.f('ix_public_indication_foundation_uri'))
        batch_op.drop_index(batch_op.f('ix_public_indication_disease_id'))
        batch_op.drop_index(batch_op.f('ix_public_indication_code'))
        batch_op.drop_index(batch_op.f('ix_public_indication_BlockId'))
        batch_op.create_unique_constraint('indication_foundation_uri_key', ['foundation_uri'])
        batch_op.create_unique_constraint('indication_disease_id_key', ['disease_id'])

    with op.batch_alter_table('drug_salt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_salt_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_salt_salt_id_fkey', 'salt', ['salt_id'], ['id'])

    with op.batch_alter_table('drug_route_metabolite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_route_metabolite_drug_route_id_fkey', 'drug_route', ['drug_route_id'], ['id'])
        batch_op.create_foreign_key('drug_route_metabolite_metabolite_id_fkey', 'metabolite', ['metabolite_id'], ['id'])

    with op.batch_alter_table('drug_route_metabolism_organ', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_route_metabolism_organ_drug_route_id_fkey', 'drug_route', ['drug_route_id'], ['id'])
        batch_op.create_foreign_key('drug_route_metabolism_organ_metabolism_organ_id_fkey', 'metabolism_organ', ['metabolism_organ_id'], ['id'])

    with op.batch_alter_table('drug_route_metabolism_enzyme', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_route_metabolism_enzyme_drug_route_id_fkey', 'drug_route', ['drug_route_id'], ['id'])
        batch_op.create_foreign_key('drug_route_metabolism_enzyme_metabolism_enzyme_id_fkey', 'metabolism_enzyme', ['metabolism_enzyme_id'], ['id'])

    with op.batch_alter_table('drug_route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_route_drug_detail_id_fkey', 'drug_detail', ['drug_detail_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('drug_route_route_id_fkey', 'route_of_administration', ['route_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('drug_receptor_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_receptor_interaction_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_receptor_interaction_receptor_id_fkey', 'receptor', ['receptor_id'], ['id'])

    with op.batch_alter_table('drug_label_variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_label_variant_variant_id_fkey', 'variant', ['variant_id'], ['id'])
        batch_op.create_foreign_key('drug_label_variant_pharmgkb_id_fkey', 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'])

    with op.batch_alter_table('drug_label_gene', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_label_gene_gene_id_fkey', 'gene', ['gene_id'], ['gene_id'])
        batch_op.create_foreign_key('drug_label_gene_pharmgkb_id_fkey', 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'])

    with op.batch_alter_table('drug_label_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_label_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_label_drug_pharmgkb_id_fkey', 'drug_label', ['pharmgkb_id'], ['pharmgkb_id'])

    with op.batch_alter_table('drug_lab_test_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_lab_test_interaction_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_lab_test_interaction_severity_id_fkey', 'severity', ['severity_id'], ['id'])
        batch_op.create_foreign_key('drug_lab_test_interaction_lab_test_id_fkey', 'lab_test', ['lab_test_id'], ['id'])

    with op.batch_alter_table('drug_interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_drug_interaction_severity_id', 'severity', ['severity_id'], ['id'])
        batch_op.create_foreign_key('drug_interaction_drug1_id_fkey', 'drug', ['drug1_id'], ['id'])
        batch_op.create_foreign_key('drug_interaction_drug2_id_fkey', 'drug', ['drug2_id'], ['id'])
        batch_op.create_foreign_key('drug_interaction_route_id_fkey', 'route_of_administration', ['route_id'], ['id'])

    with op.batch_alter_table('drug_disease_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_disease_interaction_indication_id_fkey', 'indication', ['indication_id'], ['id'])
        batch_op.create_foreign_key('drug_disease_interaction_drug_id_fkey', 'drug', ['drug_id'], ['id'])

    with op.batch_alter_table('drug_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_detail_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('drug_detail_salt_id_fkey', 'salt', ['salt_id'], ['id'])

    with op.batch_alter_table('drug_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_category_parent_id_fkey', 'drug_category', ['parent_id'], ['id'])

    with op.batch_alter_table('drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drug_category_id_fkey', 'drug_category', ['category_id'], ['id'])

    with op.batch_alter_table('detail_side_effect', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('detail_side_effect_side_effect_id_fkey', 'side_effect', ['side_effect_id'], ['id'])
        batch_op.create_foreign_key('detail_side_effect_detail_id_fkey', 'drug_detail', ['detail_id'], ['id'])

    with op.batch_alter_table('clinical_variants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_variants_gene_id_fkey', 'gene', ['gene_id'], ['gene_id'])
        batch_op.drop_index(batch_op.f('ix_public_clinical_variants_gene_id'))

    with op.batch_alter_table('clinical_variant_variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_variant_variant_clinical_variant_id_fkey', 'clinical_variants', ['clinical_variant_id'], ['id'])
        batch_op.create_foreign_key('clinical_variant_variant_variant_id_fkey', 'variant', ['variant_id'], ['id'])

    with op.batch_alter_table('clinical_variant_phenotype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_variant_phenotype_phenotype_id_fkey', 'phenotype', ['phenotype_id'], ['id'])
        batch_op.create_foreign_key('clinical_variant_phenotype_clinical_variant_id_fkey', 'clinical_variants', ['clinical_variant_id'], ['id'])

    with op.batch_alter_table('clinical_variant_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_variant_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('clinical_variant_drug_clinical_variant_id_fkey', 'clinical_variants', ['clinical_variant_id'], ['id'])

    with op.batch_alter_table('clinical_annotation_variant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_annotation_variant_variant_id_fkey', 'variant', ['variant_id'], ['id'])
        batch_op.create_foreign_key('clinical_annotation_variant_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])

    with op.batch_alter_table('clinical_annotation_phenotype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_annotation_phenotype_phenotype_id_fkey', 'phenotype', ['phenotype_id'], ['id'])
        batch_op.create_foreign_key('clinical_annotation_phenotype_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])

    with op.batch_alter_table('clinical_annotation_gene', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_annotation_gene_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])
        batch_op.create_foreign_key('clinical_annotation_gene_gene_id_fkey', 'gene', ['gene_id'], ['gene_id'])

    with op.batch_alter_table('clinical_annotation_drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_annotation_drug_drug_id_fkey', 'drug', ['drug_id'], ['id'])
        batch_op.create_foreign_key('clinical_annotation_drug_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])

    with op.batch_alter_table('clinical_ann_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_ann_history_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])
        batch_op.drop_index(batch_op.f('ix_public_clinical_ann_history_date'))
        batch_op.alter_column('clinical_annotation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('clinical_ann_evidence_publication', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_ann_evidence_publication_pmid_fkey', 'publication', ['pmid'], ['pmid'])
        batch_op.create_foreign_key('clinical_ann_evidence_publication_evidence_id_fkey', 'clinical_ann_evidence', ['evidence_id'], ['evidence_id'])

    with op.batch_alter_table('clinical_ann_evidence', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_ann_evidence_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])
        batch_op.drop_index(batch_op.f('ix_public_clinical_ann_evidence_evidence_type'))
        batch_op.alter_column('clinical_annotation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('clinical_ann_allele', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clinical_ann_allele_clinical_annotation_id_fkey', 'clinical_annotation', ['clinical_annotation_id'], ['clinical_annotation_id'])
        batch_op.drop_index(batch_op.f('ix_public_clinical_ann_allele_genotype_allele'))
        batch_op.alter_column('clinical_annotation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('automated_annotations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('automated_annotations_pmid_fkey', 'publication', ['pmid'], ['pmid'])
        batch_op.drop_index(batch_op.f('ix_public_automated_annotations_variation_id'))
        batch_op.drop_index(batch_op.f('ix_public_automated_annotations_pmid'))
        batch_op.drop_index(batch_op.f('ix_public_automated_annotations_gene_symbols'))
        batch_op.drop_index(batch_op.f('ix_public_automated_annotations_chemical_id'))


    op.create_table('case_study',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('drug_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('interaction_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='case_study_pkey')
    )
    op.create_table('user_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_progress_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_progress_pkey')
    )
    op.drop_table('unit', schema='public')
    # ### end Alembic commands ###
